version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
  php:
    build: ./
    container_name: php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html
    ports:
      - 9080:80
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 9090:80
